<?xml version="1.0" encoding="UTF-8"?><definitions name="MamMemberServices" targetNamespace="http://MamMemberServicesProcessModule/com/att/sdp/bprocess/MamMemberServicesArtifacts" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://MamMemberServicesProcessModule/com/att/sdp/bprocess/MamMemberServicesArtifacts" xmlns:wsdl0="http://SdpCommonLibrary/com/att/sdp/intf/FromMam_FeaturePermissionMailboxUpdate_Interface" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="FromMam_FeaturePermissionMailboxUpdate_InterfacePLT">
    <plnk:role name="FromMam_FeaturePermissionMailboxUpdate_InterfaceRole">
      <plnk:portType name="wsdl0:FromMam_FeaturePermissionMailboxUpdate_Interface"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="PartnerPLT">
    <plnk:role name="partnerRole">
      <plnk:portType name="wsdl0:FromMam_FeaturePermissionMailboxUpdate_Interface"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="PartnerPLT1">
    <plnk:role name="partnerRole">
      <plnk:portType name="wsdl0:FromMam_FeaturePermissionMailboxUpdate_Interface"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <import location="../intf/FromMam_FeaturePermissionMailboxUpdate_Interface.wsdl" namespace="http://SdpCommonLibrary/com/att/sdp/intf/FromMam_FeaturePermissionMailboxUpdate_Interface"/>
</definitions>